.github/workflows/ci.yml
Es una actualización de las Actions, hago merge yo mismo.
=> Actualización deployment

src/main/java/com/example/b1esimageweb/model/Photo.java, src/main/java/com/example/b1esimageweb/model/User.java, src/main/java/com/example/b1esimageweb/service/UserService.java, src/main/java/com/example/b1esimageweb/web/Security/CurrentUserDetails.java, src/main/java/com/example/b1esimageweb/web/controller/GalleryController.java, src/main/java/com/example/b1esimageweb/web/controller/UserController.java
In this commit I implemented the logic to upload profile image for a user.
=> Profile image uploads correctly

src/main/java/com/example/b1esimageweb/model/Photo.java, src/main/java/com/example/b1esimageweb/service/GalleryService.java, src/main/java/com/example/b1esimageweb/web/controller/GalleryController.java
Implementación del endpoint que retorna una foto dado su id
=> 53 us41 enpoint para ver una foto de una galeria

frontend/angular.json, frontend/package-lock.json, frontend/src/app/services/authentication.service.ts, frontend/src/app/services/gallery.service.ts, frontend/src/app/services/user.service.ts, frontend/src/environments/environment.production.ts, frontend/src/environments/environment.ts, src/main/java/com/example/b1esimageweb/web/Security/AppConfig.java, src/main/java/com/example/b1esimageweb/web/Security/WebSecurityConfig.java
He separado los path de dev y pro para ponerlo en producción.
Configuración de pro:
--configuration=production
=> Configuración de pro/dev

frontend/src/app/components/login-page/login-page.component.html, frontend/src/app/components/login-page/login-page.component.ts, frontend/src/app/components/register-page/register-page.component.html, frontend/src/app/components/register-page/register-page.component.ts
En este pull request he añadido un par de botones para mostrar las contraseñas.
Hay dos problemas, el primero es que se muestra debajo del input y seria mas estetico que estuviese en el lado.
El segundo es que para ello he tenido que añadir los links de los iconos en bootstrap y los he puesto en las paginas de login y register, no en un lugar general.
=> eye icon en la contraseña

src/main/java/com/example/b1esimageweb/repository/UserRepository.java, src/main/java/com/example/b1esimageweb/service/AuthService.java, src/main/java/com/example/b1esimageweb/service/UserService.java, src/main/java/com/example/b1esimageweb/web/Jwt/JwtAuthenticationFilter.java, src/main/java/com/example/b1esimageweb/web/Jwt/JwtTokenProvider.java, src/main/java/com/example/b1esimageweb/web/Security/AppConfig.java, src/test/java/com/example/b1esimageweb/GalleryControllerIntegrationTest.java, src/test/java/com/example/b1esimageweb/UserControllerIntegrationTest.java
Ya se actualiza bien el perfil de usuario.
=> Fixed user not found error upon updating user profile

README.md, frontend/src/app/app.module.ts, frontend/src/app/components/change-password/change-password.component.css, frontend/src/app/components/change-password/change-password.component.html, frontend/src/app/components/change-password/change-password.component.spec.ts, frontend/src/app/components/change-password/change-password.component.ts, frontend/src/app/components/edit-profile/edit-profile.component.html, frontend/src/app/components/edit-profile/edit-profile.component.ts, frontend/src/app/components/profile-page/profile-page.component.html, frontend/src/app/components/profile-page/profile-page.component.ts
interficies (per provar endpoints o veure que tal quedarà)
- dummy implementation del canvi de contrasenya
- apartats de username i description reafegits a editar perfil (no funcionen)
=> 88 us26 cambiar contraseña (no funcional)

src/main/java/com/example/b1esimageweb/service/GalleryService.java, src/main/java/com/example/b1esimageweb/web/controller/GalleryController.java, src/main/java/com/example/b1esimageweb/web/dto/PhotoDto.java
Algunos cambios para hacerlo funcionar
=> Eliminar fotos de galería

src/main/java/com/example/b1esimageweb/model/User.java, src/main/java/com/example/b1esimageweb/repository/PhotoRepository.java, src/main/java/com/example/b1esimageweb/web/controller/UserController.java, src/main/java/com/example/b1esimageweb/web/dto/PhotoDto.java, src/main/java/com/example/b1esimageweb/web/dto/UserUpdateDto.java
Se ha añadido un nuevo campo description al user.
=> 100 us 27 actualizar entidad user

frontend/angular.json, frontend/package-lock.json, frontend/package.json, frontend/src/app/app.module.ts, frontend/src/app/components/gallery/gallery.component.css, frontend/src/app/components/gallery/gallery.component.html, frontend/src/app/components/gallery/gallery.component.ts, frontend/src/app/components/home-page/home-page.component.html, frontend/src/app/components/modal/modal.component.html, frontend/src/app/components/modal/modal.component.spec.ts, frontend/src/app/components/modal/modal.component.ts, frontend/src/app/components/upload-photo/upload-photo.component.ts, frontend/src/app/services/gallery.service.ts, frontend/src/main.ts, frontend/tsconfig.app.json, frontend/tsconfig.spec.json
1. He creado un componente modal que es reutilizable y puede ser personalizado desde cualquier otro componente.
2. Se ha implementado la funcionalidad de eliminar fotos.
3. Se ha gestionado el manejo de posibles errores que puedan surgir al intentar eliminar una foto.
4. Queda pendiente la modificación de los parámetros de la foto al momento de subirla. Actualmente, si no has actualizado la página, no es posible eliminarla ya que no se guarda el id.
Espero tu respuesta para verificar que todo esta correcto.
=> Eliminar fotos galeria5 1

frontend/src/app/components/change-password/change-password.component.html, frontend/src/app/components/change-password/change-password.component.ts, frontend/src/app/components/edit-profile/edit-profile.component.ts, frontend/src/app/components/home-page/home-page.component.ts, frontend/src/app/components/profile-page/profile-page.component.html, frontend/src/app/components/profile-page/profile-page.component.ts, frontend/src/app/services/user.service.ts, src/main/java/com/example/b1esimageweb/service/UserService.java
us 2.6 canviar contrasenya
- spinner quan dones click a canviar
- casos d'error controlats
=> 88 us26 cambiar contraseña

src/main/java/com/example/b1esimageweb/repository/UserRepository.java, src/main/java/com/example/b1esimageweb/service/SearchService.java, src/main/java/com/example/b1esimageweb/web/controller/SearchController.java
New endpoint that search users from a search criteria (part of username).
=> backend endpoint for searching users

frontend/src/app/components/edit-profile/edit-profile.component.ts, frontend/src/app/components/home-page/home-page.component.ts, frontend/src/app/components/upload-photo/upload-photo.component.ts, frontend/src/app/services/gallery.service.ts
- He solucionado el error de las fotos que se subian sin el id, ahora estas fotos que estan recien subidas se pueden eliminar sin problema.   
- He añadido un mensaje de error para cuando no detecte el idGallery
-Con esto daria por terminada esta historia de usuario. 
Espero tu respuesta para verificar que todo esta correcto.
=> us delete finished photo.

src/main/java/com/example/b1esimageweb/service/AlbumService.java, src/main/java/com/example/b1esimageweb/service/GalleryService.java, src/main/java/com/example/b1esimageweb/service/UserService.java, src/main/java/com/example/b1esimageweb/web/dto/PhotoDto.java
He arreglado el get, ahora proporciona también la description.
Al subir photo desde gallery se crea una descripción con "".
=> Fix Campo Descripción en Photo

frontend/src/app/components/edit-profile/edit-profile.component.ts, frontend/src/app/components/navbar/navbar.component.ts, frontend/src/app/services/global-data.service.ts
ya se ve la foto de la navbar después de recargar en cualquier pagina
=> foto perfil navbar fix

frontend/src/app/components/albums/albums.component.ts, frontend/src/app/components/edit-gallery/edit-gallery.component.css, frontend/src/app/components/edit-gallery/edit-gallery.component.ts, frontend/src/app/components/gallery/gallery.component.css, frontend/src/app/components/gallery/gallery.component.ts, frontend/src/app/components/upload-photo/upload-photo.component.ts, frontend/src/app/services/gallery.service.ts
-He finalizado la conexión del backend para permitir la edición del nombre y la descripción de la foto.
Espero tu respuesta para verificar que todo esta correcto.
=> Editar campos imagen3 3

src/main/java/com/example/b1esimageweb/service/SearchService.java, src/main/java/com/example/b1esimageweb/web/controller/SearchController.java
changed endpoint to return photo data and make it easy for frontend development.
=> endpoint returns photo data

src/main/java/com/example/b1esimageweb/service/AlbumService.java, src/main/java/com/example/b1esimageweb/web/controller/AlbumController.java
endpoint for getting album by id
=> 155 us 37 endpoint get album by

frontend/src/app/components/navbar/navbar.component.css, frontend/src/app/components/navbar/navbar.component.html, frontend/src/app/components/navbar/navbar.component.ts, frontend/src/app/services/user.service.ts
falta el disseny de les cards d'usuaris trobats (foto principalment, per a poder tenir-la com a referencia per a posicionar el nom i el botó)
la search bar tan gran en el mode responsive tapa alguns usuaris trobats
=> search bar 

src/main/java/com/example/b1esimageweb/repository/AlbumRepository.java, src/main/java/com/example/b1esimageweb/repository/PhotoRepository.java, src/main/java/com/example/b1esimageweb/service/AlbumService.java, src/main/java/com/example/b1esimageweb/web/controller/AlbumController.java
I implemented the endpoint to get albums by a username.
=> Implemented the endpoint to get Albums By a Username

frontend/src/app/components/albums/albums.component.html, frontend/src/app/components/albums/albums.component.ts, frontend/src/app/components/gallery/gallery.component.css, frontend/src/app/components/gallery/gallery.component.html, frontend/src/app/components/navbar/navbar.component.css, frontend/src/app/components/navbar/navbar.component.html, frontend/src/app/components/profile-page/profile-page.component.html, frontend/src/app/components/profile-page/profile-page.component.ts, frontend/src/app/components/secondary-navbar/secondary-navbar.component.css, frontend/src/app/components/secondary-navbar/secondary-navbar.component.html, frontend/src/app/components/upload-photo/upload-photo.component.ts, frontend/src/app/components/user-profile/user-profile.component.html, frontend/src/app/components/user-profile/user-profile.component.ts, frontend/src/app/services/albums.service.ts
Afegida implementació de veure àlbums d'altres usuaris, completa fins a on em permeten les implementacions actuals (amb altres features com veure àlbum s'hauran de canviar coses).
Alguns fixes de responsitivity.
=> ver perfil otros usuarios amb àlbums

src/main/java/com/example/b1esimageweb/service/AlbumService.java, src/main/java/com/example/b1esimageweb/service/GalleryService.java, src/main/java/com/example/b1esimageweb/web/Security/AppConfig.java, src/main/java/com/example/b1esimageweb/web/controller/AlbumController.java, src/main/java/com/example/b1esimageweb/web/controller/GalleryController.java, src/main/java/com/example/b1esimageweb/web/controller/UserController.java
He protegido los endpoints PUT y POST mas importantes que puedan causar posible problemas de seguridad e accesos invalidos.
Ahora un usuario no debe poder modificar informacion de otro usuario mediante un endpoint.
=> Comprobacion token en los endpoints

frontend/src/app/components/edit-albums/edit-albums.component.css, frontend/src/app/components/edit-albums/edit-albums.component.html, frontend/src/app/components/edit-albums/edit-albums.component.ts
- Integrado la funcionalidad para eliminar álbums, solo esta la parte del front porque falta el endpoint por parte del back.
Espero tu respuesta para verificar que todo esta correcto.
=> creating functionality to delete albums

src/main/java/com/example/b1esimageweb/Exceptions/UnauthorizedAlbumDeletionException.java, src/main/java/com/example/b1esimageweb/repository/PhotoRepository.java, src/main/java/com/example/b1esimageweb/service/AlbumService.java, src/main/java/com/example/b1esimageweb/web/controller/AlbumController.java
En este commint he implementado 2 endpoints:
1.US 3.10 "/albumInfo/{username}" que retorna en formato key:value los id's y nombres de álbumes que tenga un usuario especificado por el username medianto endpoint
2. US 3.9  "/album/delete" que elimina los albumes de un usuario y tambien las fotos que estan en ese album. En caso que la foto este compartida con la galeria, solo la borra del album
=> Implementado el endpoint que retorna ids y nombre de albums / endploint delete albums

frontend/src/app/components/albums/albums.component.html, frontend/src/app/components/albums/albums.component.ts, frontend/src/app/components/edit-albums/edit-albums.component.html, frontend/src/app/components/edit-albums/edit-albums.component.ts, frontend/src/app/components/edit-gallery/edit-gallery.component.html, frontend/src/app/components/edit-gallery/edit-gallery.component.ts, frontend/src/app/components/edit-profile/edit-profile.component.css, frontend/src/app/components/edit-profile/edit-profile.component.html, frontend/src/app/components/edit-profile/edit-profile.component.ts, frontend/src/app/components/gallery/gallery.component.html, frontend/src/app/components/profile-page/profile-page.component.css, frontend/src/app/components/profile-page/profile-page.component.html, frontend/src/app/components/secondary-navbar/secondary-navbar.component.ts, frontend/src/app/services/albums.service.ts
- Implementé la funcionalidad para eliminar fotos desde el backend.
- Realizo una verificación para asegurarme de que, tras hacer clic en eliminar, si el usuario queda sin álbumes, se redirige automáticamente a la sección de álbumes.
- Ajusté los estilos en las galerías y álbumes para corregir la aparición de líneas blancas, especialmente alrededor de los botones, ya que carecían de la sombra y el degradado que se habían aplicado a galeria y álbumes.
- Modifiqué los estilos de la sección información, ya que anteriormente utilizaba estilos no responsivos que no mantenían el mismo margen que las demás secciones. Ahora, he adoptado clases de Bootstrap para lograr una apariencia más consistente.
- He implementado la función de …
=> delete finished albums

src/main/java/com/example/b1esimageweb/model/User.java, src/main/java/com/example/b1esimageweb/repository/PhotoRepository.java, src/main/java/com/example/b1esimageweb/repository/UserRepository.java, src/main/java/com/example/b1esimageweb/service/UserService.java, src/main/java/com/example/b1esimageweb/web/controller/AlbumController.java, src/main/java/com/example/b1esimageweb/web/controller/GalleryController.java, src/main/java/com/example/b1esimageweb/web/controller/UserController.java, src/main/resources/application.properties
He implementado todo lo que es seguir usuarios, dejar de seguir un usuario, ver lista de usuarios que siguen y lista de usuarios a los que sigues. Estas listas serán del usuario especificado mediante el endpoint.
=> Us 2.8 followers

frontend/src/app/components/profile-page/profile-page.component.css, frontend/src/app/components/profile-page/profile-page.component.html, frontend/src/app/components/profile-page/profile-page.component.ts, frontend/src/app/components/user-profile/user-profile.component.css, frontend/src/app/components/user-profile/user-profile.component.html, frontend/src/app/components/user-profile/user-profile.component.ts, frontend/src/app/services/followers.service.spec.ts, frontend/src/app/services/followers.service.ts
1. He implementado la vista de los seguidores tanto para el usuario en cuestión como para los usuarios a los que visitas. 
2. También está terminada la funcionalidad de seguir usuarios.
Espero tu respuesta para verificar que todo está correcto.
=> 2 8seguir usuarios
